### ISSUE TITLE
Incorrect notebook reference in fine-tuning entity extraction notebook 

### ISSUE THREAD

**Issue by jamesrmccall** [databricks-demos/dbdemos-notebooks#45]
In the fine-tuning entity extraction notebook (product_demos/Data-Science/llm-fine-tuning/02-entity-extraction-fine-tuning/02.1-llm-entity-extraction-drug-fine-tuning.py) on line 86 it references the "llm-evaluation notebook" as ../02 when it is actually "product_demos/Data-Science/llm-fine-tuning/03-chatbot-rag-fine-tuning/03.2-llm-evaluation.py". This model deployment is a prerequisite for the rest of the notebook, especially the baseline eval, to succeed.

**Comment by QuentinAmbard** [comment]
thanks! It should be better in the new version!
